manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nicekeyboards
      url-base: https://github.com/nicekeyboards
    - name: GabrielNicolasLopez
      url-base: https://github.com/GabrielNicolasLopez
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    
    - name: zmk-behavior-alt-tab-encoder
      remote: GabrielNicolasLopez
      revision: main
  self:
    path: config
